oj:
  config:
    check-in-award: 10
    default-role-id: 1
    check-max-award: 50
    ac-problem-award-rate: 0.5
    file-base-url: ${OJ_FILE_BASE_URL:/tmp/oj_files}
    default-password: ${OJ_DEFAULT_PASSWORD:}
    captcha-type: MATH

common:
  config:

    captcha-code-lifespan: 120
    email-code-lifespan: 120
