oj:
  config:
    check-in-award: 10
    default-role-id: 1
    check-max-award: 50
    ac-problem-award-rate: 0.5
    file-base-url: "E:/cach/temp"
    default-password: change-this-default-password
    captcha-type: MATH

common:
  config:

    captcha-code-lifespan: 120
    email-code-lifespan: 120
