server:
  port: 8082
spring:
  config:
    name: judge-server

  rabbitmq:
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1

#共用一个数据库
oj:
  db:
    database: db_problem
  knife4j:
    resource: com.anishan.judge

  minio:
    bucket-name: case


# judge的url
judge:
  url: http://localhost:5050
  config:
    max-concurrency: ${OJ_JUDGE_MAX_CONCURRENCY:4}
    max-submissions: ${OJ_JUDGE_MAX_SUBMISSIONS:1}
    queue-capacity: ${OJ_JUDGE_QUEUE_CAPACITY:200}
