server:
  port: 8082
spring:
  config:
    name: judge-server

  rabbitmq:
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10

#共用一个数据库
oj:
  db:
    database: db_problem
  knife4j:
    resource: com.anishan.judge


# judge的url
judge:
  url: http://localhost:5050
