error_log /var/log/nginx/error.log notice;

server {
    listen 80;
    server_name yantuocode.cn;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name yantuocode.cn;

    resolver 127.0.0.11 valid=10s ipv6=off;

    ssl_certificate /etc/ssl/certs/yantuocode.cn.pem;
    ssl_certificate_key /etc/ssl/certs/yantuocode.cn.key;
    ssl_session_timeout 5m;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location ^~ /api/ {
        set $gateway_upstream http://gateway-server;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass $gateway_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 200m;
    }
}
