server:
  port: 8088
spring:
  config:
    name: content-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
oj:
  db:
    database: db_content

  knife4j:
    resource: com.anishan.content

  minio:
    url: ${OJ_MINIO_URL:http://localhost:9000}
    access-key: ${OJ_MINIO_ACCESS_KEY:}
    secret-key: ${OJ_MINIO_SECRET_KEY:}
    bucket-name: uploads

