spring:
  datasource:
    url: jdbc:mysql://${oj.db.host:8.149.133.76}:${oj.db.port:3306}/${oj.db.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${oj.db.un:root}
    password: ${oj.db.pw:change-this-db-password}

  hikari:
    connection-timeout: 10000
    validation-timeout: 3000
    idle-timeout: 60000
    login-timeout: 5
    max-lifetime: 60000
    maximum-pool-size: 10
    minimum-idle: 5
    read-only: false


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: on
    lazy-loading-enabled: on

  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0